on:
  release:
    types:
      - published

name: release

permissions: {} # All jobs define their needed permissions below.

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install pypa/build
        run: python -m pip install -U build

      - name: Build distributions
        run: python -m build

      - name: Store distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: upload distributions to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Used to authenticate to PyPI via OIDC.

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
